name: Python tests

on: [ push, pull_request ]

jobs:
  test:
    name: Python tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rep
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          node-version: '20'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest ./tests